{% set name = "check_shapes" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b699fcb1e60bb17e2c97007e444b89eeeea2a9102ff11d61fb52454af5348403

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - dropstackframe >=0.1.0
    - lark >=1.1.0

test:
  imports:
    - check_shapes
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    
outputs:
  - name: check_shapes
  - name: check-shapes
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("check_shapes", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - check_shapes

about:
  home: https://github.com/GPflow/check_shapes
  summary: 'Library for annotating and checking tensor shapes.'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - westinhuang
